#!/usr/bin/env node
/**
 * Generates api/API_INDEX.md — a token-lean map of every route and shared helper
 * in the API, so a session can find code by name instead of reading index.js.
 *
 * Run after any change that adds/moves/removes a route:  npm run index:api
 *
 * Intentionally dependency-free and regex-based. It is a lookup table, not a
 * compiler — if a line is formatted oddly it gets skipped rather than crashing.
 */
const fs = require('fs');
const path = require('path');

const API_DIR = path.join(__dirname, '..');
const OUT_FILE = path.join(API_DIR, 'API_INDEX.md');

const SCAN_DIRS = ['', '_routes', '_lib'];
// index.legacy.js is the pre-split monolith, kept for diffing — indexing it
// would double-count every route.
const SKIP_FILES = new Set(['API_INDEX.md', 'index.legacy.js']);

const ROUTE_RE = /^\s*(?:app|router)\.(get|post|put|patch|delete|use)\(\s*['"`]([^'"`]+)['"`]/;
const FN_RE = /^(?:async\s+)?function\s+([A-Za-z0-9_$]+)/;
const CONST_FN_RE = /^const\s+([A-Za-z0-9_$]+)\s*=\s*(?:async\s*)?\(/;

/** Pull the comment block immediately above a line, as a one-line summary. */
function commentAbove(lines, idx) {
  const out = [];
  for (let i = idx - 1; i >= 0; i--) {
    const t = lines[i].trim();
    if (!t) { if (out.length) break; continue; }
    if (t.startsWith('//')) { out.unshift(t.replace(/^\/\/+\s?/, '')); continue; }
    if (t.startsWith('*') || t.startsWith('/*')) {
      const c = t.replace(/^\/?\*+\s?/, '').replace(/\*\/$/, '').trim();
      if (c) out.unshift(c);
      continue;
    }
    break;
  }
  return out.join(' ').replace(/\|/g, '\\|').slice(0, 160);
}

/** Read forward from a route's opening line to guess its auth posture. */
function authHint(lines, idx) {
  const body = lines.slice(idx, idx + 40).join('\n');
  const tags = [];
  if (/getAuthenticatedUserId/.test(body)) tags.push('auth');
  if (/from\(['"`]moderators['"`]\)/.test(body)) tags.push('mod');
  if (/validateApiKey/.test(body)) tags.push('api-key');
  if (/INTERNAL_SECRET|x-internal-secret/i.test(body)) tags.push('internal');
  return tags.length ? tags.join('+') : 'public';
}

function scanFile(absPath, relPath) {
  const lines = fs.readFileSync(absPath, 'utf8').split(/\r?\n/);
  const routes = [];
  const helpers = [];

  lines.forEach((line, i) => {
    const r = ROUTE_RE.exec(line);
    if (r) {
      const [, verb, routePath] = r;
      // app.use(...) with a bare path is middleware mounting, not an endpoint.
      if (verb === 'use' && !routePath.startsWith('/api')) return;
      routes.push({
        method: verb.toUpperCase(),
        path: routePath,
        line: i + 1,
        file: relPath,
        auth: authHint(lines, i),
        desc: commentAbove(lines, i),
      });
      return;
    }
    const f = FN_RE.exec(line) || CONST_FN_RE.exec(line);
    if (f) {
      helpers.push({ name: f[1], line: i + 1, file: relPath, desc: commentAbove(lines, i) });
    }
  });

  return { routes, helpers };
}

function collectFiles() {
  const files = [];
  for (const dir of SCAN_DIRS) {
    const abs = path.join(API_DIR, dir);
    if (!fs.existsSync(abs)) continue;
    for (const name of fs.readdirSync(abs)) {
      if (!name.endsWith('.js') || SKIP_FILES.has(name)) continue;
      const full = path.join(abs, name);
      if (!fs.statSync(full).isFile()) continue;
      files.push({ abs: full, rel: path.posix.join('api', dir, name).replace('api//', 'api/') });
    }
  }
  return files;
}

/** Group routes by their /api/<segment>/ prefix so related endpoints sit together. */
function groupKey(routePath) {
  const parts = routePath.split('/').filter(Boolean); // ['api', 'mod', 'board-builder']
  if (parts[0] !== 'api') return parts[0] || 'misc';
  if (['mod', 'admin', 'internal', 'upload', 'overlay', 'tools', 'user', 'users'].includes(parts[1])) {
    return parts[2] ? `${parts[1]}/${parts[2]}` : parts[1];
  }
  return parts[1] || 'misc';
}

function main() {
  const files = collectFiles();
  const allRoutes = [];
  const allHelpers = [];
  for (const f of files) {
    const { routes, helpers } = scanFile(f.abs, f.rel);
    allRoutes.push(...routes);
    allHelpers.push(...helpers);
  }

  const groups = new Map();
  for (const r of allRoutes) {
    const k = groupKey(r.path);
    if (!groups.has(k)) groups.set(k, []);
    groups.get(k).push(r);
  }

  const out = [];
  out.push('# API Index');
  out.push('');
  out.push('> Generated by `api/scripts/buildApiIndex.js` — do not edit by hand.');
  out.push('> Regenerate with `npm run index:api` after adding, moving, or removing a route.');
  out.push('');
  out.push(`${allRoutes.length} routes across ${files.length} files. \`auth\` column: `);
  out.push('`public` = no auth, `auth` = requires a signed-in user, `mod` = moderator check, ');
  out.push('`internal` = cron/webhook secret, `api-key` = overlay key.');
  out.push('');

  for (const k of [...groups.keys()].sort()) {
    out.push(`## /${k}`);
    out.push('');
    out.push('| Method | Path | Auth | Location | Notes |');
    out.push('|---|---|---|---|---|');
    for (const r of groups.get(k).sort((a, b) => a.path.localeCompare(b.path))) {
      out.push(`| ${r.method} | \`${r.path}\` | ${r.auth} | \`${r.file}:${r.line}\` | ${r.desc} |`);
    }
    out.push('');
  }

  out.push('## Shared helpers');
  out.push('');
  out.push('| Function | Location | Notes |');
  out.push('|---|---|---|');
  for (const h of allHelpers.sort((a, b) => a.name.localeCompare(b.name))) {
    out.push(`| \`${h.name}\` | \`${h.file}:${h.line}\` | ${h.desc} |`);
  }
  out.push('');

  fs.writeFileSync(OUT_FILE, out.join('\n'), 'utf8');
  console.log(`Wrote ${OUT_FILE}`);
  console.log(`  ${allRoutes.length} routes, ${allHelpers.length} helpers, ${files.length} files`);
}

main();
